name: todo_remind
description: A professional todo app with gamification and reminders
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^19.4.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  timezone: ^0.10.1
  shared_preferences: ^2.2.2
  table_calendar: ^3.2.0
  package_info_plus: ^8.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  # Declare your assets folder
  assets:
    - lib/assets/reminderIcon.webp
    - lib/assets/TDsplash.webp

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/reminderIcon.webp"

flutter_native_splash:
  color: "#6366F1"   # Background color (your app’s primary color)
  image: "lib/assets/TDsplash.webp"   # Your logo (must exist in assets/icon/)
  android: true
  ios: true
  web: false
